language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NWvYBdygvzvhOPlt9Pfq/fdzdP/5KFpU2A9xoFIOaSsVy37P2N1SQ0FWCfCDfgSVvbue/ZpqqevTp8jAS+FNHqU2Fvf7oeEXuzAvRC/9Rjmd18dnLCMOROYhuudDOMYHgUQDBAr6p1EuQ9ctGxFtedU4hJPVgSfEPb8pv6Aq4x0=
  file:
    - "remark-comment-config.js"
    - "remark-comment-config.min.js"
  on:
    tags: true
