language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: NPY9xkGBFI81Cipj90ncffU/e6yBgzV9NUhRNAYsXol7rH7RaOdYXrMTwrDtrp8UUY8iKuFDED0u6t/+BQ3heeGnglLY7/7eCwMff23zXNVdy4sVO2RqTmjCqGR43Im3EGLXmWQNH7D8FPbqvlPeCXYRvqYF1m12TvX+V1xIfdM=
  file:
    - "remark-comment-config.js"
    - "remark-comment-config.min.js"
  on:
    tags: true
    node: '9.0'
